/*============================================================================
    test_dante_av_txrx_integrity.c — Dante A/V TX+RX audio integrity test

    Verifies that audio data received via DEP shared memory matches the
    known sine wave pattern generated by audiotestsrc on the TX side.

    TX side (same machine or --tx):
      audiotestsrc (440Hz sine, 48kHz, S32LE, vol=0.8)
        -> audioresampler -> dantedepaudiosink (DEP shm)

    RX side (--rx):
      dantedepaudiosrc -> audioresampler -> verify sink
        (compares each sample against expected sine wave)

    Usage:
      TX: ./test_dante_av_txrx_integrity --tx [--log file] [dvr_path] [dep_name]
      RX: ./test_dante_av_txrx_integrity --rx [--log file] [dvr_path] [dep_name]
      Both: ./test_dante_av_txrx_integrity [--log file] [dvr_path] [dep_name]
      Default = both TX and RX in same process.

    Log:
      Auto-generates: dante_av_{tx|rx|txrx}_YYYYMMDD_HHMMSS.log
      Or specify: --log <filename>

    Defaults:
      dvr_path = /var/run/dante/dvr
      dep_name = DanteEP
============================================================================*/
#define _POSIX_C_SOURCE 200809L

#include "zst_bus.h"
#include "zst_clock.h"
#include "zst_element.h"
#include "zst_pad.h"
#include "zst_pipeline.h"
#include "zst_scheduler.h"
#include "zst_buffer.h"
#include "zstreamer/elements/zst_audio_resampler.h"
#include "zstreamer/elements/zst_audio_test_src.h"
#include "zstreamer/elements/zst_dante_dep_audio.h"
#include "zstreamer/elements/zst_dante_session.h"
#include "zstreamer/elements/zst_dante_video_coordinator.h"
#include "zstreamer/elements/zst_dante_udp_sink.h"
#include "zstreamer/elements/zst_dante_udp_source.h"
#include "zstreamer/elements/zst_h264_decoder.h"
#include "zstreamer/elements/zst_video_test_src.h"
#include "zstreamer/elements/zst_x264_encoder.h"

#include <errno.h>
#include <fcntl.h>
#include <math.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/wait.h>

/* ── DEP ABI ────────────────────────────────────────────────────────────── */
#define DEP_HEADER_MAGIC UINT32_C(0x50525354)
/* Track per-TX-flow RTP send stats */
typedef struct {
    uint32_t flow_index;
    uint32_t channel_index;
    uint32_t port;
    char receiver_address[INET_ADDRSTRLEN];
    int reported;           /* 1 after first stats print */
    uint64_t last_packets;  /* previous packets-sent count */
    uint64_t last_errors;   /* previous send-errors count */
} rtp_tx_track_t;

typedef struct {
    uint32_t flow_index;
    uint32_t channel_index;
    uint32_t port;
    char receiver_address[INET_ADDRSTRLEN];
    char transmitter_address[INET_ADDRSTRLEN];
    int reported;           /* 1 after first stats print */
    uint64_t last_packets;  /* previous packets-received count */
    uint64_t last_rejected; /* previous packets-rejected count */
} rtp_rx_track_t;

#define MAX_RTP_TX_TRACK 8
#define MAX_RTP_RX_TRACK 8

static rtp_tx_track_t g_rtp_tx_track[MAX_RTP_TX_TRACK];
static rtp_rx_track_t g_rtp_rx_track[MAX_RTP_RX_TRACK];
static int g_rtp_tx_count = 0;
static int g_rtp_rx_count = 0;

typedef struct {
    uint32_t magic, object_bytes, metadata_bytes, flags;
    uint32_t tx_offset, rx_offset, timing_offset, reset_serial;
    uint32_t sample_rate, encoding, samples_per_channel, bytes_per_channel;
    uint32_t tx_channels, rx_channels, audio_reserved[2];
    uint32_t epoch_seconds, epoch_samples, samples_per_period, period_alignment;
    uint64_t period_count;
    uint32_t drift_ppb, monotonic_alignment;
    uint64_t monotonic_ns;
} dep_diag_header_t;

typedef enum { MODE_BOTH, MODE_TX, MODE_RX } run_mode_t;

/* ── Sine wave verification state ──────────────────────────────────────── */
typedef struct {
    /* TX parameters (must match audiotestsrc defaults in test) */
    double frequency;    /* Hz */
    double volume;       /* 0.0 – 1.0 */
    uint32_t sample_rate;

    /* Running phase accumulator */
    double phase;

    /* Statistics */
    uint64_t total_samples;
    uint64_t matched_samples;   /* within tolerance */
    uint64_t mismatched_samples;
    uint64_t max_error_sample;  /* sample index of worst mismatch */
    double   max_error_value;   /* worst absolute error */

    /* Tolerance: allowed deviation as fraction of full-scale S32 */
    double tolerance;
} sine_verify_state_t;

/* ── Globals ──────────────────────────────────────────────────────────── */
static volatile sig_atomic_t g_stop;
static zst_scheduler_t*      g_scheduler;

static void on_signal(int sig) {
    (void)sig;
    g_stop = 1;
    /* Do NOT call zst_scheduler_stop() here — not async-signal-safe.
     * The main loop checks g_stop and calls scheduler stop properly. */
}

static uint64_t monotonic_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

/* ── Helpers ───────────────────────────────────────────────────────────── */
static int set_str(zst_element_t* e, const char* n, const char* v) {
    if (zst_element_set_property_string(e, n, v) == ZST_OK) return 1;
    fprintf(stderr, "  [WARN] set %s=%s FAILED\n", n, v); return 0;
}
static int set_uint(zst_element_t* e, const char* n, uint32_t v) {
    if (zst_element_set_property_uint(e, n, v) == ZST_OK) return 1;
    fprintf(stderr, "  [WARN] set %s=%u FAILED\n", n, v); return 0;
}
static const char* sname(zst_state_t s) {
    switch (s) {
        case ZST_STATE_NULL:    return "NULL";
        case ZST_STATE_READY:   return "READY";
        case ZST_STATE_PAUSED:  return "PAUSED";
        case ZST_STATE_PLAYING: return "PLAYING";
        default: return "?";
    }
}

static void print_dep_ep(zst_element_t* el, const char* label) {
    char v[64];
    const char* k[] = {"active","sample-rate","period-count",
                       "overrun-count","underflow-count",NULL};
    printf("  %s:\n", label);
    for (int i = 0; k[i]; ++i)
        if (zst_element_get_property(el, k[i], v, sizeof(v)) == ZST_OK)
            printf("    %-18s = %s\n", k[i], v);
}

static void print_states(zst_pipeline_t* p) {
    printf("  Pipeline states (%u elements):\n", p->nb_elements);
    for (uint32_t i = 0; i < p->nb_elements; ++i)
        printf("    %-30s = %s\n",
               p->elements[i]->ops ? p->elements[i]->ops->name : "?",
               sname((zst_state_t)atomic_load(&p->elements[i]->state)));
}

static void drain_bus(zst_bus_t* bus, zst_element_t* coord,
                      int* tx_f, int* rx_f, int* err) {
    zst_event_t* ev = NULL;
    while (zst_bus_pop(bus, &ev, 0) == ZST_OK && ev) {
        switch (ev->type) {
        case ZST_EVENT_ERROR:
            fprintf(stderr, "  [BUS ERR] from %s: %s (code=%d)\n",
                    ev->src && ev->src->ops ? ev->src->ops->name : "?",
                    ev->as.error.message, ev->as.error.result);
            if (err) (*err)++;
            break;
        case ZST_EVENT_WARNING:
            fprintf(stderr, "  [BUS WARN] %s\n", ev->as.error.message);
            break;
        case ZST_EVENT_DANTE_FLOW_CREATED:
            if (ev->as.dante_flow.flow.direction == ZST_DANTE_FLOW_TX) {
                if (coord && zst_dante_video_coordinator_apply_flow(
                        coord, &ev->as.dante_flow.flow) == ZST_OK) {
                    printf("  [BUS] TX video flow idx=%u ch=%u port=%u\n",
                           ev->as.dante_flow.flow.flow_index,
                           ev->as.dante_flow.flow.channel_index,
                           ev->as.dante_flow.flow.port);
                    /* Track this flow for RTP stats */
                    if (g_rtp_tx_count < MAX_RTP_TX_TRACK) {
                        rtp_tx_track_t* t = &g_rtp_tx_track[g_rtp_tx_count++];
                        t->flow_index    = ev->as.dante_flow.flow.flow_index;
                        t->channel_index = ev->as.dante_flow.flow.channel_index;
                        t->port          = ev->as.dante_flow.flow.port;
                        strncpy(t->receiver_address,
                                ev->as.dante_flow.flow.receiver_address ? ev->as.dante_flow.flow.receiver_address : "?",
                                sizeof(t->receiver_address) - 1);
                        t->reported      = 0;
                        t->last_packets  = 0;
                        t->last_errors   = 0;
                    }
                    if (tx_f) (*tx_f)++;
                }
            } else if (ev->as.dante_flow.flow.direction == ZST_DANTE_FLOW_RX) {
                if (coord && zst_dante_video_coordinator_apply_flow(
                        coord, &ev->as.dante_flow.flow) == ZST_OK) {
                    printf("  [BUS] RX video flow idx=%u ch=%u port=%u\n",
                           ev->as.dante_flow.flow.flow_index,
                           ev->as.dante_flow.flow.channel_index,
                           ev->as.dante_flow.flow.port);
                    /* Track this flow for RTP receive stats */
                    if (g_rtp_rx_count < MAX_RTP_RX_TRACK) {
                        rtp_rx_track_t* t = &g_rtp_rx_track[g_rtp_rx_count++];
                        t->flow_index    = ev->as.dante_flow.flow.flow_index;
                        t->channel_index = ev->as.dante_flow.flow.channel_index;
                        t->port          = ev->as.dante_flow.flow.port;
                        strncpy(t->receiver_address,
                                ev->as.dante_flow.flow.receiver_address ? ev->as.dante_flow.flow.receiver_address : "?",
                                sizeof(t->receiver_address) - 1);
                        strncpy(t->transmitter_address,
                                ev->as.dante_flow.flow.transmitter_address ? ev->as.dante_flow.flow.transmitter_address : "?",
                                sizeof(t->transmitter_address) - 1);
                        t->reported      = 0;
                        t->last_packets  = 0;
                        t->last_rejected = 0;
                    }
                    if (rx_f) (*rx_f)++;
                }
            }
            break;
        case ZST_EVENT_DANTE_FLOW_DELETED:
            if (coord)
                (void)zst_dante_video_coordinator_remove_flow(
                    coord, &ev->as.dante_flow.flow);
            break;
        default: break;
        }
        zst_event_destroy(ev);
    }
}

static void inspect_dep(const char* name) {
    char path[512]; struct stat st;
    snprintf(path, sizeof(path), "/dev/shm/%s", name);
    printf("[SHM] %s: ", path);
    if (stat(path, &st) != 0) { fprintf(stderr, "MISSING\n"); return; }
    int fd = open(path, O_RDONLY);
    if (fd < 0) { fprintf(stderr, "open fail\n"); return; }
    void* m = mmap(NULL, st.st_size, PROT_READ, MAP_SHARED, fd, 0);
    close(fd);
    if (m == MAP_FAILED) { fprintf(stderr, "mmap fail\n"); return; }
    dep_diag_header_t* h = m;
    printf("magic=0x%08X %s rate=%u period=%u pc=%llu serial=%u\n",
           h->magic, h->magic == DEP_HEADER_MAGIC ? "OK" : "BAD",
           h->sample_rate, h->samples_per_period,
           (unsigned long long)h->period_count, h->reset_serial);
    munmap(m, st.st_size);
}

/* ══════════════════════════════════════════════════════════════════════════ */
/*  Sine wave verification                                                  */
/*  Matches audiotestsrc's fast_sine_from_phase() with volume=0.8           */
/* ══════════════════════════════════════════════════════════════════════════ */

static void sine_verify_init(sine_verify_state_t* sv, uint32_t sample_rate,
                             double frequency, double volume) {
    memset(sv, 0, sizeof(*sv));
    sv->frequency  = frequency;
    sv->volume     = volume;
    sv->sample_rate = sample_rate;
    sv->phase      = 0.0;
    sv->tolerance  = 0.02;  /* 2% of full-scale S32 ≈ ±419430 LSB */
}

static double sine_verify_next_expected(sine_verify_state_t* sv) {
    /* Reproduce audiotestsrc's fast_sine_from_phase() */
    const double pi = 3.14159265358979323846;
    const double two_pi = 6.28318530717958647692;
    double x = sv->phase * two_pi;
    if (x > pi) x -= two_pi;

    const double b = 4.0 / pi;
    const double c = -4.0 / (pi * pi);
    const double p = 0.225;

    double y = b * x + c * x * (x < 0.0 ? -x : x);
    y = p * (y * (y < 0.0 ? -y : y) - y) + y;

    /* Advance phase */
    double step = (double)sv->sample_rate > 0
                ? sv->frequency / (double)sv->sample_rate : 0.0;
    sv->phase += step;
    while (sv->phase >= 1.0) sv->phase -= 1.0;
    while (sv->phase < 0.0) sv->phase += 1.0;

    /* Apply volume and clamp */
    y *= sv->volume;
    if (y > 1.0) y = 1.0;
    if (y < -1.0) y = -1.0;
    return y;
}

static void sine_verify_process_buffer(sine_verify_state_t* sv,
                                       const int32_t* samples,
                                       uint32_t nb_samples) {
    for (uint32_t i = 0; i < nb_samples; i++) {
        double expected = sine_verify_next_expected(sv);
        /* S32LE: 1.0 → INT32_MAX, -1.0 → INT32_MIN */
        double expected_s32 = expected * 2147483647.0;
        double actual_s32   = (double)samples[i];
        double err = actual_s32 - expected_s32;
        double abs_err = err < 0.0 ? -err : err;

        sv->total_samples++;
        double tol_s32 = sv->tolerance * 2147483647.0;
        if (abs_err <= tol_s32) {
            sv->matched_samples++;
        } else {
            sv->mismatched_samples++;
            if (abs_err > sv->max_error_value) {
                sv->max_error_value = abs_err;
                sv->max_error_sample = sv->total_samples;
            }
        }
    }
}

static void sine_verify_reset(sine_verify_state_t* sv) {
    uint64_t total   = sv->total_samples;
    uint64_t matched = sv->matched_samples;
    uint64_t mism    = sv->mismatched_samples;
    sv->total_samples     = 0;
    sv->matched_samples   = 0;
    sv->mismatched_samples = 0;
    sv->max_error_value   = 0.0;
    sv->max_error_sample  = 0;
    /* Print summary before reset */
    printf("    verify: total=%llu matched=%llu mismatch=%llu (%.2f%%)\n",
           (unsigned long long)total, (unsigned long long)matched,
           (unsigned long long)mism,
           total > 0 ? (double)matched * 100.0 / (double)total : 0.0);
}

/* ══════════════════════════════════════════════════════════════════════════ */
/*  Custom RX verify sink — replaces fake_sink for RX mode                  */
/* ══════════════════════════════════════════════════════════════════════════ */

typedef struct {
    sine_verify_state_t verify;
    uint64_t total_buffers;
    uint64_t total_samples;
    uint64_t channel0_samples;
    uint64_t nonzero_samples;
    uint64_t positive_crossings;
    uint64_t peak_abs;
    long double sum_sq;
    int signal_started;
    int32_t last_channel0;
    int have_last_channel0;
    char wav_path[256];
    FILE* wav_fp;
    uint32_t wav_bytes;
} rx_verify_sink_t;

static zst_result_t rx_verify_open(zst_element_t* el) {
    rx_verify_sink_t* s = el->priv;
    s->total_buffers = 0;
    s->total_samples = 0;
    s->channel0_samples = 0;
    s->nonzero_samples = 0;
    s->positive_crossings = 0;
    s->peak_abs = 0;
    s->sum_sq = 0.0;
    s->signal_started = 0;
    s->last_channel0 = 0;
    s->have_last_channel0 = 0;
    sine_verify_init(&s->verify, 48000, 440.0, 0.8);

    if (s->wav_path[0] != '\0') {
        s->wav_fp = fopen(s->wav_path, "wb");
        if (s->wav_fp) {
            uint8_t hdr[44] = {0};
            memcpy(hdr, "RIFF", 4);
            memcpy(hdr + 8, "WAVE", 4);
            memcpy(hdr + 12, "fmt ", 4);
            uint32_t fmt_len = 16;
            uint16_t fmt_tag = 1; /* PCM */
            uint16_t channels = 2;
            uint32_t rate = 48000;
            uint16_t bits = 16;
            uint32_t byte_rate = rate * channels * (bits / 8);
            uint16_t block_align = channels * (bits / 8);
            memcpy(hdr + 16, &fmt_len, 4);
            memcpy(hdr + 20, &fmt_tag, 2);
            memcpy(hdr + 22, &channels, 2);
            memcpy(hdr + 24, &rate, 4);
            memcpy(hdr + 28, &byte_rate, 4);
            memcpy(hdr + 32, &block_align, 2);
            memcpy(hdr + 34, &bits, 2);
            memcpy(hdr + 36, "data", 4);
            fwrite(hdr, 1, 44, s->wav_fp);
            s->wav_bytes = 0;
            printf("  [WAV] Recording RX audio to %s (48kHz, 16-bit stereo PCM)\n", s->wav_path);
        } else {
            fprintf(stderr, "  [WARN] Failed to open WAV recording file: %s (errno=%d: %s)\n",
                    s->wav_path, errno, strerror(errno));
        }
    }
    return ZST_OK;
}

static zst_result_t rx_verify_process(zst_element_t* el,
                                      zst_buffer_t* in,
                                      zst_buffer_t** out) {
    if (!el) return ZST_ERROR;
    rx_verify_sink_t* s = el->priv;
    (void)out;
    if (!in) return ZST_ERROR;

    /* Verify audio data integrity.  Exact sample matching is kept for same-process
     * tests; signal metrics below validate real cross-device runs where the RX
     * starts at an arbitrary sine phase. */
    if (in->memory.data && in->memory.size > 0) {
        const int32_t* samples = (const int32_t*)in->memory.data;
        uint32_t nb_samples = (uint32_t)(in->memory.size / sizeof(int32_t));
        uint32_t channels = 2;
        const zst_audio_frame_t* af = in->payload;
        if (af && af->channels > 0) channels = af->channels;
        sine_verify_process_buffer(&s->verify, samples, nb_samples);
        s->total_samples += nb_samples;

        if (s->wav_fp) {
            for (uint32_t i = 0; i < nb_samples; i++) {
                int16_t s16 = (int16_t)(samples[i] >> 16);
                fwrite(&s16, sizeof(int16_t), 1, s->wav_fp);
            }
            s->wav_bytes += nb_samples * sizeof(int16_t);
        }
        for (uint32_t i = 0; i < nb_samples; i += channels) {
            int32_t sample = samples[i];
            int64_t value = sample;
            uint64_t abs_value = (uint64_t)(value < 0 ? -value : value);
            if (!s->signal_started) {
                if (abs_value < 21474836ULL) continue; /* ignore startup silence (<1% FS) */
                s->signal_started = 1;
                s->last_channel0 = sample;
                s->have_last_channel0 = 1;
            }
            if (sample != 0) s->nonzero_samples++;
            if (abs_value > s->peak_abs) s->peak_abs = abs_value;
            s->sum_sq += (long double)value * (long double)value;
            if (s->have_last_channel0 && s->last_channel0 <= 0 && sample > 0)
                s->positive_crossings++;
            s->last_channel0 = sample;
            s->have_last_channel0 = 1;
            s->channel0_samples++;
        }
    }
    s->total_buffers++;
    return ZST_OK;
}

static zst_result_t rx_verify_get_property(zst_element_t* el,
                                           const char* name,
                                           char* value_out,
                                           size_t max_len) {
    rx_verify_sink_t* s = el->priv;
    if (strcmp(name, "total-buffers") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->total_buffers);
        return ZST_OK;
    } else if (strcmp(name, "total-samples") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->total_samples);
        return ZST_OK;
    } else if (strcmp(name, "matched-samples") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->verify.matched_samples);
        return ZST_OK;
    } else if (strcmp(name, "mismatched-samples") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->verify.mismatched_samples);
        return ZST_OK;
    } else if (strcmp(name, "max-error") == 0) {
        snprintf(value_out, max_len, "%.1f (at sample %llu)",
                 s->verify.max_error_value,
                 (unsigned long long)s->verify.max_error_sample);
        return ZST_OK;
    } else if (strcmp(name, "integrity-pct") == 0) {
        double pct = s->verify.total_samples > 0
            ? (double)s->verify.matched_samples * 100.0 /
              (double)s->verify.total_samples
            : 0.0;
        snprintf(value_out, max_len, "%.4f%%", pct);
        return ZST_OK;
    } else if (strcmp(name, "signal-rms-pct") == 0) {
        double rms = s->channel0_samples > 0
            ? sqrt((double)(s->sum_sq / (long double)s->channel0_samples)) : 0.0;
        snprintf(value_out, max_len, "%.2f%%", rms * 100.0 / 2147483647.0);
        return ZST_OK;
    } else if (strcmp(name, "signal-peak-pct") == 0) {
        snprintf(value_out, max_len, "%.2f%%",
                 (double)s->peak_abs * 100.0 / 2147483647.0);
        return ZST_OK;
    } else if (strcmp(name, "signal-frequency-hz") == 0) {
        double seconds = s->channel0_samples > 0
            ? (double)s->channel0_samples / 48000.0 : 0.0;
        double hz = seconds > 0.0 ? (double)s->positive_crossings / seconds : 0.0;
        snprintf(value_out, max_len, "%.2f", hz);
        return ZST_OK;
    } else if (strcmp(name, "signal-ok") == 0) {
        double seconds = s->channel0_samples > 0
            ? (double)s->channel0_samples / 48000.0 : 0.0;
        double hz = seconds > 0.0 ? (double)s->positive_crossings / seconds : 0.0;
        double peak_pct = (double)s->peak_abs * 100.0 / 2147483647.0;
        int ok = s->channel0_samples >= 4800 && s->nonzero_samples > 0 &&
                 peak_pct >= 50.0 && peak_pct <= 95.0 && hz >= 420.0 && hz <= 460.0;
        snprintf(value_out, max_len, "%s", ok ? "true" : "false");
        return ZST_OK;
    }
    return ZST_ERROR;
}

static zst_result_t rx_verify_sink_push(zst_pad_t* pad, zst_buffer_t* buf) {
    zst_buffer_t* out = NULL;
    return rx_verify_process(pad ? pad->parent : NULL, buf, &out);
}

static zst_result_t rx_verify_close(zst_element_t* el) {
    rx_verify_sink_t* s = el->priv;
    if (s && s->wav_fp) {
        uint32_t riff_size = 36 + s->wav_bytes;
        uint32_t data_size = s->wav_bytes;
        fseek(s->wav_fp, 4, SEEK_SET);
        fwrite(&riff_size, 4, 1, s->wav_fp);
        fseek(s->wav_fp, 40, SEEK_SET);
        fwrite(&data_size, 4, 1, s->wav_fp);
        fclose(s->wav_fp);
        s->wav_fp = NULL;
        printf("  [WAV] Finished recording: %u bytes (%.2f s) written to %s\n",
               s->wav_bytes, (double)s->wav_bytes / (48000.0 * 2.0 * 2.0), s->wav_path);
    }
    return ZST_OK;
}

static zst_element_ops_t g_rx_verify_ops = {
    .name         = "rx-verify-sink",
    .open         = rx_verify_open,
    .process      = rx_verify_process,
    .close        = rx_verify_close,
    .get_property = rx_verify_get_property,
};

static zst_element_t* rx_verify_sink_create(const char* wav_path) {
    rx_verify_sink_t* priv = calloc(1, sizeof(*priv));
    if (!priv) return NULL;
    if (wav_path && wav_path[0]) {
        strncpy(priv->wav_path, wav_path, sizeof(priv->wav_path) - 1);
    }

    zst_element_t* el = zst_element_create(&g_rx_verify_ops, priv);
    if (!el) { free(priv); return NULL; }

    zst_pad_t* sink = zst_pad_create("sink", ZST_PAD_SINK);
    if (sink) sink->push = rx_verify_sink_push;
    if (!sink || zst_element_add_pad(el, sink) != ZST_OK) {
        if (sink) zst_pad_destroy(sink);
        zst_element_destroy(el);
        return NULL;
    }
    return el;
}

/* ══════════════════════════════════════════════════════════════════════════ */
/*  Custom RX video verify sink — consumes decoded H.264 frames              */
/* ══════════════════════════════════════════════════════════════════════════ */

typedef struct {
    uint64_t total_frames;
    uint64_t total_bytes;
    uint64_t keyframes;
    uint32_t width;
    uint32_t height;
    uint32_t format;
    int have_geometry;          /* set once first frame parsed */
    double mean_luma;           /* running mean of luma plane (Y) */
} rx_video_sink_t;

static zst_result_t rx_video_open(zst_element_t* el) {
    rx_video_sink_t* s = el->priv;
    s->total_frames   = 0;
    s->total_bytes    = 0;
    s->keyframes      = 0;
    s->width          = 0;
    s->height         = 0;
    s->format         = 0;
    s->have_geometry  = 0;
    s->mean_luma      = 0.0;
    return ZST_OK;
}

static zst_result_t rx_video_process(zst_element_t* el,
                                     zst_buffer_t* in,
                                     zst_buffer_t** out) {
    if (!el) return ZST_ERROR;
    rx_video_sink_t* s = el->priv;
    (void)out;
    if (!in) return ZST_ERROR;
    if (in->type != ZST_BUFFER_VIDEO_FRAME) return ZST_OK;

    s->total_frames++;
    s->total_bytes += in->memory.size;
    if (in->flags & ZST_BUFFER_FLAG_KEYFRAME) s->keyframes++;

    const zst_video_frame_t* vf = in->payload;
    if (vf) {
        if (!s->have_geometry) {
            s->width  = vf->width;
            s->height = vf->height;
            s->format = vf->format;
            s->have_geometry = 1;
        }
        /* Running mean of luma plane (first plane / Y). */
        if (vf->plane[0] && vf->stride[0] > 0 && vf->height > 0) {
            uint64_t sum = 0;
            for (uint32_t y = 0; y < vf->height; y++)
                sum += vf->plane[0][y * vf->stride[0]];
            double frame_mean = (double)sum / (double)vf->height;
            s->mean_luma += (frame_mean - s->mean_luma) / (double)s->total_frames;
        }
    }
    return ZST_OK;
}

static zst_result_t rx_video_sink_push(zst_pad_t* pad, zst_buffer_t* buf) {
    zst_buffer_t* out = NULL;
    return rx_video_process(pad ? pad->parent : NULL, buf, &out);
}

static zst_result_t rx_video_get_property(zst_element_t* el,
                                          const char* name,
                                          char* value_out,
                                          size_t max_len) {
    rx_video_sink_t* s = el->priv;
    if (strcmp(name, "total-frames") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->total_frames);
        return ZST_OK;
    } else if (strcmp(name, "total-bytes") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->total_bytes);
        return ZST_OK;
    } else if (strcmp(name, "keyframes") == 0) {
        snprintf(value_out, max_len, "%llu",
                 (unsigned long long)s->keyframes);
        return ZST_OK;
    } else if (strcmp(name, "width") == 0) {
        snprintf(value_out, max_len, "%u", s->width);
        return ZST_OK;
    } else if (strcmp(name, "height") == 0) {
        snprintf(value_out, max_len, "%u", s->height);
        return ZST_OK;
    } else if (strcmp(name, "format") == 0) {
        snprintf(value_out, max_len, "%u", s->format);
        return ZST_OK;
    } else if (strcmp(name, "mean-luma") == 0) {
        snprintf(value_out, max_len, "%.2f", s->mean_luma);
        return ZST_OK;
    }
    return ZST_ERROR;
}

static zst_element_ops_t g_rx_video_ops = {
    .name         = "rx-video-sink",
    .open         = rx_video_open,
    .process      = rx_video_process,
    .get_property = rx_video_get_property,
};

static zst_element_t* rx_video_sink_create(void) {
    rx_video_sink_t* priv = calloc(1, sizeof(*priv));
    if (!priv) return NULL;

    zst_element_t* el = zst_element_create(&g_rx_video_ops, priv);
    if (!el) { free(priv); return NULL; }

    zst_pad_t* sink = zst_pad_create("sink", ZST_PAD_SINK);
    if (sink) sink->push = rx_video_sink_push;
    if (!sink || zst_element_add_pad(el, sink) != ZST_OK) {
        if (sink) zst_pad_destroy(sink);
        zst_element_destroy(el);
        return NULL;
    }
    return el;
}

/* ══════════════════════════════════════════════════════════════════════════ */
/*  Tee logging — write stdout+stderr to both terminal and log file          */
/* ══════════════════════════════════════════════════════════════════════════ */
static int g_log_fd = -1;  /* log file fd for cleanup */

static void tee_child_func(int read_fd, int term_fd, FILE* log_fp) {
    char buf[8196];
    ssize_t n;
    while ((n = read(read_fd, buf, sizeof(buf))) > 0) {
        (void)write(term_fd, buf, (size_t)n);
        (void)fwrite(buf, 1, (size_t)n, log_fp);
        fflush(log_fp);
    }
}

static int setup_tee(const char* log_path, int original_fd) {
    int pipefd[2];
    if (pipe(pipefd) < 0) return -1;

    FILE* log_fp = fopen(log_path, "a");
    if (!log_fp) { close(pipefd[0]); close(pipefd[1]); return -1; }

    pid_t pid = fork();
    if (pid == 0) {
        /* Child: read pipe → write to terminal + log file */
        close(pipefd[1]);
        tee_child_func(pipefd[0], original_fd, log_fp);
        fclose(log_fp);
        close(pipefd[0]);
        _exit(0);
    }
    /* Parent: close read end, return write end */
    close(pipefd[0]);
    return pipefd[1];
}

static void setup_log_tee(const char* log_path) {
    /* Save original stdout/stderr fds */
    int orig_stdout = dup(STDOUT_FILENO);
    int orig_stderr = dup(STDERR_FILENO);
    if (orig_stdout < 0 || orig_stderr < 0) return;

    int tee_out = setup_tee(log_path, orig_stdout);
    int tee_err = setup_tee(log_path, orig_stderr);

    if (tee_out >= 0) dup2(tee_out, STDOUT_FILENO);
    if (tee_err >= 0) dup2(tee_err, STDERR_FILENO);

    /* Keep log file fd for cleanup */
    if (tee_out >= 0) g_log_fd = tee_out;
    else if (tee_err >= 0) g_log_fd = tee_err;
}

/* ══════════════════════════════════════════════════════════════════════════ */
/*  Main                                                                    */
/* ══════════════════════════════════════════════════════════════════════════ */
int main(int argc, char** argv)
{
    /* ── Parse arguments ─────────────────────────────────────────────── */
    run_mode_t mode = MODE_BOTH;
    const char* dvr_path = "/var/run/dante/dvr";
    const char* dep_name = "DanteEP";
    const char* log_path = NULL;
    const char* record_wav_path = NULL;
    char auto_wav[256] = {0};

    int arg_idx = 1;
    while (arg_idx < argc) {
        if (strcmp(argv[arg_idx], "--tx") == 0) {
            mode = MODE_TX; arg_idx++;
        } else if (strcmp(argv[arg_idx], "--rx") == 0) {
            mode = MODE_RX; arg_idx++;
        } else if (strcmp(argv[arg_idx], "--log") == 0 && arg_idx + 1 < argc) {
            log_path = argv[++arg_idx]; arg_idx++;
        } else if (strcmp(argv[arg_idx], "--record-wav") == 0 ||
                   strcmp(argv[arg_idx], "--dump-wav") == 0) {
            if (arg_idx + 1 < argc && argv[arg_idx + 1][0] != '-') {
                record_wav_path = argv[++arg_idx];
            } else {
                record_wav_path = "auto";
            }
            arg_idx++;
        } else {
            break;
        }
    }
    if (arg_idx < argc) dvr_path = argv[arg_idx++];
    if (arg_idx < argc) dep_name = argv[arg_idx++];

    /* ── Auto-generate log / wav file name based on mode ───────────── */
    char auto_log[256];
    time_t now = time(NULL);
    struct tm* tm = localtime(&now);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y%m%d_%H%M%S", tm);

    if (record_wav_path && strcmp(record_wav_path, "auto") == 0) {
        snprintf(auto_wav, sizeof(auto_wav), "dante_rx_%s.wav", ts);
        record_wav_path = auto_wav;
    }

    if (!log_path) {
        const char* mode_tag = (mode == MODE_TX) ? "tx"
                             : (mode == MODE_RX) ? "rx" : "txrx";
        snprintf(auto_log, sizeof(auto_log), "dante_av_%s_%s.log", mode_tag, ts);
        log_path = auto_log;
    }

    /* ── Setup log tee (before any output) ───────────────────────────── */
    setup_log_tee(log_path);
    fprintf(stderr, "[LOG] Tee output to: %s\n", log_path);

    /* Ignore SIGPIPE — tee child may die first on Ctrl+C, breaking the pipe */
    signal(SIGPIPE, SIG_IGN);

    const char* mode_str = (mode == MODE_TX) ? "TX-only"
                         : (mode == MODE_RX) ? "RX-only" : "TX+RX";

    uint32_t sr = 48000, ch = 2, spb = 4096;
    uint32_t vw = 320, vh = 240, vfps = 30;

    printf("=== Dante A/V %s Integrity Test ===\n", mode_str);
    printf("DVR: %s | DEP: %s\n", dvr_path, dep_name);
    printf("Log: %s\n", log_path);
    printf("Audio: %uHz %uch S32LE (buf=%u) 440Hz sine vol=0.8\n",
           sr, ch, spb);
    printf("Video: %ux%u@%ufps\n", vw, vh, vfps);
    if (record_wav_path) {
        printf("WAV Dump: %s (48kHz, 16-bit stereo PCM)\n", record_wav_path);
    }
    printf("Verify: sine wave ±2%% tolerance\n");
    printf("Ctrl+C to stop.\n");
    printf("==========================================\n\n");

    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);

    inspect_dep(dep_name); printf("\n");

    /* ── Create elements ─────────────────────────────────────────────── */
    printf("[1] Creating elements...\n");
    zst_pipeline_t* pipe = zst_pipeline_create();
    zst_clock_t*    clock = zst_clock_system_create();

    /* TX elements */
    zst_element_t* tx_audio_src = (mode != MODE_RX)
                                ? zst_audio_test_src_create() : NULL;
    zst_element_t* tx_resampler = (mode != MODE_RX)
                                ? zst_audio_resampler_create(
                                      (int)sr, (int)ch, "S32LE") : NULL;
    zst_element_t* tx_dep_sink  = (mode != MODE_RX)
                                ? zst_dante_dep_audio_sink_create() : NULL;
    zst_element_t* video_src    = (mode != MODE_RX)
                                ? zst_video_test_src_create() : NULL;
    zst_element_t* encoder      = (mode != MODE_RX)
                                ? zst_x264_encoder_create() : NULL;

    /* RX elements */
    zst_element_t* rx_dep_src   = (mode != MODE_TX)
                                ? zst_dante_dep_audio_source_create() : NULL;
    zst_element_t* rx_resampler = (mode != MODE_TX)
                                ? zst_audio_resampler_create(
                                      (int)sr, (int)ch, "S32LE") : NULL;
    zst_element_t* rx_sink      = (mode != MODE_TX)
                                ? rx_verify_sink_create(record_wav_path) : NULL;
    zst_element_t* rx_video_dec = (mode != MODE_TX)
                                ? zst_h264_decoder_create() : NULL;
    zst_element_t* rx_video_snk = (mode != MODE_TX)
                                ? rx_video_sink_create() : NULL;

    /* Shared */
    zst_element_t* session     = zst_dante_session_create(dvr_path);
    zst_element_t* coordinator = zst_dante_video_coordinator_create();

    int nelem = 0;
    if (tx_audio_src) nelem++;
    if (tx_resampler) nelem++;
    if (tx_dep_sink) nelem++;
    if (rx_dep_src) nelem++;
    if (rx_resampler) nelem++;
    if (rx_sink) nelem++;
    if (video_src) nelem++;
    if (encoder) nelem++;
    if (rx_video_dec) nelem++;
    if (rx_video_snk) nelem++;
    nelem += 2; /* session + coordinator */

    if (!pipe || !clock || !session || !coordinator) {
        fprintf(stderr, "[FATAL] core creation failed\n"); return 1;
    }
    if (rx_sink) {
        printf("  [OK] %d elements created (RX verify sink enabled).\n", nelem);
    } else {
        printf("  [OK] %d elements created.\n", nelem);
    }

    /* ── Configure ───────────────────────────────────────────────────── */
    printf("[2] Configuring...\n");

    if (tx_audio_src) {
        set_uint(tx_audio_src, "sample-rate", sr);
        set_uint(tx_audio_src, "channels", ch);
        set_str(tx_audio_src, "sample-format", "S32LE");
        set_uint(tx_audio_src, "samples-per-buffer", spb);
        set_str(tx_audio_src, "use-clock", "true");
        set_str(tx_audio_src, "real-time-pacing", "true");
        /* Keep defaults: wave=sine, frequency=440, volume=0.8 */
    }
    if (tx_resampler) {
        set_str(tx_resampler, "asrc-mode", "pts");
        set_str(tx_resampler, "max-drift-ppm", "2000");
        set_uint(tx_resampler, "drift-check-interval", 4);
        set_uint(tx_resampler, "block-samples", 512);
    }
    if (tx_dep_sink) {
        set_str(tx_dep_sink, "shm-name", dep_name);
        { char c[32]; snprintf(c, sizeof(c), "0,1");
          set_str(tx_dep_sink, "channels", c); }
        { char r[32]; snprintf(r, sizeof(r), "%u", sr);
          set_str(tx_dep_sink, "expected-sample-rate", r); }
        set_uint(tx_dep_sink, "queue-periods", 2048);
    }
    if (rx_dep_src) {
        set_str(rx_dep_src, "shm-name", dep_name);
        { char c[32]; snprintf(c, sizeof(c), "0,1");
          set_str(rx_dep_src, "channels", c); }
        set_uint(rx_dep_src, "queue-periods", 2048);
        { char r[32]; snprintf(r, sizeof(r), "%u", sr);
          set_str(rx_dep_src, "expected-sample-rate", r); }
    }
    if (video_src) {
        set_uint(video_src, "width", vw);
        set_uint(video_src, "height", vh);
        set_uint(video_src, "fps", vfps);
        set_str(video_src, "use-clock", "true");
        set_str(video_src, "real-time-pacing", "true");
    }
    if (encoder) {
        set_str(encoder, "preset", "ultrafast");
        set_str(encoder, "tune", "zerolatency");
        { char f[32]; snprintf(f, sizeof(f), "%u/1", vfps);
          set_str(encoder, "fps", f); }
        set_uint(encoder, "gop-size", vfps);
    }

    if (rx_video_dec) {
        set_uint(rx_video_dec, ZST_H264_DECODER_PROP_THREADS, 0);
    }

    /* Always advertise at least 1 RX channel — some DVC firmwares reject
     * start messages with zero rxVideoChannels even for TX-only sessions. */
    set_uint(session, "tx-video-channels", (mode != MODE_RX) ? 1 : 0);
    set_uint(session, "rx-video-channels", 1);

    if (tx_audio_src) zst_element_set_clock(tx_audio_src, clock);
    if (video_src)    zst_element_set_clock(video_src, clock);
    printf("  [OK] Configuration done.\n");

    /* ── Add to pipeline ─────────────────────────────────────────────── */
    printf("[3] Adding to pipeline...\n");
    zst_pipeline_add(pipe, coordinator);
    if (video_src)    zst_pipeline_add(pipe, video_src);
    if (encoder)      zst_pipeline_add(pipe, encoder);
    if (tx_audio_src) zst_pipeline_add(pipe, tx_audio_src);
    if (tx_resampler) zst_pipeline_add(pipe, tx_resampler);
    if (tx_dep_sink)  zst_pipeline_add(pipe, tx_dep_sink);
    if (rx_dep_src)   zst_pipeline_add(pipe, rx_dep_src);
    if (rx_resampler) zst_pipeline_add(pipe, rx_resampler);
    if (rx_sink)      zst_pipeline_add(pipe, rx_sink);
    if (rx_video_dec) zst_pipeline_add(pipe, rx_video_dec);
    if (rx_video_snk) zst_pipeline_add(pipe, rx_video_snk);
    printf("  [OK] %u elements.\n", pipe->nb_elements);

    /* ── Link TX audio ───────────────────────────────────────────────── */
    if (tx_audio_src && tx_resampler && tx_dep_sink) {
        printf("[4] Linking TX audio: src -> resampler -> dep_sink\n");
        zst_pad_link(zst_element_get_pad(tx_audio_src, "src"),
                     zst_element_get_pad(tx_resampler, "sink"));
        zst_pad_link(zst_element_get_pad(tx_resampler, "src"),
                     zst_element_get_pad(tx_dep_sink, "sink"));
    }

    /* ── Link RX audio ───────────────────────────────────────────────── */
    if (rx_dep_src && rx_resampler && rx_sink) {
        printf("[5] Linking RX audio: dep_src -> resampler -> verify_sink\n");
        zst_pad_link(zst_element_get_pad(rx_dep_src, "src"),
                     zst_element_get_pad(rx_resampler, "sink"));
        zst_pad_link(zst_element_get_pad(rx_resampler, "src"),
                     zst_element_get_pad(rx_sink, "sink"));
    }

    /* ── Link video TX ───────────────────────────────────────────────── */
    if (video_src && encoder && coordinator) {
        printf("[6] Linking video TX: src -> encoder -> coordinator\n");
        if (zst_pad_link(zst_element_get_pad(video_src, "src"),
                         zst_element_get_pad(encoder, "sink")) != ZST_OK)
            fprintf(stderr, "  [WARN] video src -> encoder link failed\n");
        zst_dante_video_coordinator_attach_session(coordinator, session);
        zst_pad_t* tx_pad =
            zst_dante_video_coordinator_request_tx_input_pad(coordinator, 0);
        if (tx_pad) {
            if (zst_pad_link(zst_element_get_pad(encoder, "src"), tx_pad) != ZST_OK)
                fprintf(stderr, "  [WARN] encoder -> coordinator link failed\n");
        } else {
            fprintf(stderr, "  [WARN] TX pad request failed\n");
        }
    }

    /* ── Link video RX ───────────────────────────────────────────────── */
    if (coordinator && rx_video_dec && rx_video_snk) {
        printf("[6b] Linking video RX: coordinator -> h264dec -> rx_video_sink\n");
        (void)zst_dante_video_coordinator_attach_session(coordinator, session);
        zst_pad_t* rx_pad =
            zst_dante_video_coordinator_request_rx_output_pad(coordinator, 0);
        if (rx_pad) {
            if (zst_pad_link(rx_pad,
                             zst_element_get_pad(rx_video_dec, "sink")) != ZST_OK)
                fprintf(stderr, "  [WARN] RX pad -> decoder link failed\n");
            if (zst_pad_link(zst_element_get_pad(rx_video_dec, "src"),
                             zst_element_get_pad(rx_video_snk, "sink")) != ZST_OK)
                fprintf(stderr, "  [WARN] decoder -> video sink link failed\n");
        } else {
            fprintf(stderr, "  [WARN] RX pad request failed\n");
        }
    }

    /* ── Start pipeline ──────────────────────────────────────────────── */
    printf("[7] Starting pipeline...\n");
    zst_pipeline_set_clock(pipe, clock);
    zst_pipeline_set_state(pipe, ZST_STATE_PLAYING);
    session->bus = pipe->bus;
    if (zst_element_set_state(session, ZST_STATE_PLAYING) != ZST_OK)
        fprintf(stderr, "  [WARN] DVR session start failed\n");
    else
        printf("  [OK] DVR session PLAYING\n");
    print_states(pipe);

    /* ── Scheduler ───────────────────────────────────────────────────── */
    printf("\n[8] Starting scheduler...\n");
    zst_scheduler_config_t cfg = {
        .mode = ZST_SCHEDULER_MULTI_THREAD,
        .worker_threads = 4
    };
    g_scheduler = zst_scheduler_create(&cfg);
    zst_scheduler_attach(g_scheduler, pipe);
    pthread_t sthr;
    pthread_create(&sthr, NULL,
                   (void* (*)(void*))zst_scheduler_run, g_scheduler);
    printf("  [OK] Scheduler running.\n\n");

    /* ── Monitor ─────────────────────────────────────────────────────── */
    uint64_t t0 = monotonic_ms(), last_p = t0;
    uint64_t last_tx_pc = 0, last_rx_pc = 0;
    int tx_flows = 0, rx_flows = 0, errs = 0;

    while (!g_stop) {
        usleep(200000);
        uint64_t now = monotonic_ms();
        drain_bus(pipe->bus, coordinator, &tx_flows, &rx_flows, &errs);

        if (now - last_p >= 3000) {
            printf("[%lus] tx_flows=%d rx_flows=%d errors=%d\n",
                   (unsigned long)((now - t0) / 1000),
                   tx_flows, rx_flows, errs);

            /* Print per-TX-flow RTP send stats */
            for (int i = 0; i < g_rtp_tx_count; i++) {
                rtp_tx_track_t* t = &g_rtp_tx_track[i];
                zst_element_t* sink = zst_dante_video_coordinator_get_tx_udp_sink(
                    coordinator, t->flow_index);
                if (sink) {
                    char v[64];
                    uint64_t pkts = 0, bytes = 0, errs_val = 0;
                    if (zst_element_get_property(sink, ZST_DANTE_UDP_SINK_PROP_PACKETS_SENT, v, sizeof(v)) == ZST_OK)
                        pkts = strtoull(v, NULL, 0);
                    if (zst_element_get_property(sink, ZST_DANTE_UDP_SINK_PROP_BYTES_SENT, v, sizeof(v)) == ZST_OK)
                        bytes = strtoull(v, NULL, 0);
                    if (zst_element_get_property(sink, ZST_DANTE_UDP_SINK_PROP_SEND_ERRORS, v, sizeof(v)) == ZST_OK)
                        errs_val = strtoull(v, NULL, 0);
                    uint64_t delta_pkts = pkts - t->last_packets;
                    uint64_t delta_err  = errs_val - t->last_errors;
                    t->last_packets = pkts;
                    t->last_errors  = errs_val;
                    printf("  [RTP TX flow %u] dst=%s:%u sent=%llu (+%llu) err=%llu (+%llu) bytes=%llu\n",
                           t->flow_index, t->receiver_address, t->port,
                           pkts, delta_pkts, errs_val, delta_err, bytes);
                    if (!t->reported && pkts > 0) {
                        printf("  [RTP TX] first packet sent! flow %u -> %s:%u\n",
                               t->flow_index, t->receiver_address, t->port);
                        t->reported = 1;
                    }
                } else {
                    printf("  [RTP TX flow %u] sink not found\n", t->flow_index);
                }
            }

            /* Print per-RX-flow RTP receive stats */
            for (int i = 0; i < g_rtp_rx_count; i++) {
                rtp_rx_track_t* t = &g_rtp_rx_track[i];
                zst_element_t* source = zst_dante_video_coordinator_get_rx_udp_source(
                    coordinator, t->flow_index);
                if (source) {
                    char v[64];
                    uint64_t pkts = 0, bytes = 0, rejected = 0, truncated = 0;
                    uint64_t rtp_pkts = 0, rtp_lost = 0, rtp_ooo = 0, loss_ppm = 0;
                    char last_addr[INET_ADDRSTRLEN] = "";
                    uint64_t last_size = 0;
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_PACKETS_RECEIVED, v, sizeof(v)) == ZST_OK)
                        pkts = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_BYTES_RECEIVED, v, sizeof(v)) == ZST_OK)
                        bytes = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_PACKETS_REJECTED, v, sizeof(v)) == ZST_OK)
                        rejected = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_PACKETS_TRUNCATED, v, sizeof(v)) == ZST_OK)
                        truncated = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_LAST_PACKET_ADDRESS, last_addr, sizeof(last_addr)) != ZST_OK)
                        last_addr[0] = '\0';
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_LAST_PACKET_SIZE, v, sizeof(v)) == ZST_OK)
                        last_size = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_RTP_PACKETS, v, sizeof(v)) == ZST_OK)
                        rtp_pkts = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_RTP_LOST, v, sizeof(v)) == ZST_OK)
                        rtp_lost = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_RTP_OUT_OF_ORDER, v, sizeof(v)) == ZST_OK)
                        rtp_ooo = strtoull(v, NULL, 0);
                    if (zst_element_get_property(source, ZST_DANTE_UDP_SOURCE_PROP_RTP_LOSS_RATE_PPM, v, sizeof(v)) == ZST_OK)
                        loss_ppm = strtoull(v, NULL, 0);
                    uint64_t delta_pkts = pkts - t->last_packets;
                    uint64_t delta_rej  = rejected - t->last_rejected;
                    t->last_packets = pkts;
                    t->last_rejected = rejected;
                    printf("  [RTP RX flow %u] local=%s:%u from=%s received=%llu (+%llu) rejected=%llu (+%llu) truncated=%llu bytes=%llu last=%s/%llu rtp=%llu lost=%llu ooo=%llu loss=%.4f%%\n",
                           t->flow_index, t->receiver_address, t->port,
                           t->transmitter_address, pkts, delta_pkts,
                           rejected, delta_rej, truncated, bytes,
                           last_addr[0] ? last_addr : "-", last_size,
                           rtp_pkts, rtp_lost, rtp_ooo, (double)loss_ppm / 10000.0);
                    if (!t->reported && pkts > 0) {
                        printf("  [RTP RX] first packet received! flow %u <- %s:%u\n",
                               t->flow_index, t->transmitter_address, t->port);
                        t->reported = 1;
                    }
                } else {
                    printf("  [RTP RX flow %u] source not found\n", t->flow_index);
                }
            }

            if (tx_dep_sink) {
                print_dep_ep(tx_dep_sink, "TX dep_sink");
                char v[64];
                if (zst_element_get_property(tx_dep_sink, "period-count",
                                             v, sizeof(v)) == ZST_OK) {
                    uint64_t pc = strtoull(v, NULL, 10);
                    printf("    tx_delta: %llu\n",
                           (unsigned long long)(pc - last_tx_pc));
                    last_tx_pc = pc;
                }
            }

            if (tx_resampler) {
                char adj[64], tot_in[64], tot_out[64];
                printf("  TX resampler (ASRC):\n");
                if (zst_element_get_property(tx_resampler, "drift-adjust-count", adj, sizeof(adj)) == ZST_OK)
                    printf("    drift-adjusts       = %s\n", adj);
                if (zst_element_get_property(tx_resampler, "total-input-samples", tot_in, sizeof(tot_in)) == ZST_OK)
                    printf("    total-input-samples = %s\n", tot_in);
                if (zst_element_get_property(tx_resampler, "total-output-samples", tot_out, sizeof(tot_out)) == ZST_OK)
                    printf("    total-output-samples= %s\n", tot_out);
            }

            if (rx_dep_src) {
                print_dep_ep(rx_dep_src, "RX dep_src");
                char v[64];
                if (zst_element_get_property(rx_dep_src, "period-count",
                                             v, sizeof(v)) == ZST_OK) {
                    uint64_t pc = strtoull(v, NULL, 10);
                    printf("    rx_delta: %llu\n",
                           (unsigned long long)(pc - last_rx_pc));
                    last_rx_pc = pc;
                }
            }

            /* Verify sink stats */
            if (rx_sink) {
                char v[64];
                printf("  RX verify sink:\n");
                if (zst_element_get_property(rx_sink, "total-buffers",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    total-buffers       = %s\n", v);
                if (zst_element_get_property(rx_sink, "total-samples",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    total-samples       = %s\n", v);
                if (zst_element_get_property(rx_sink, "matched-samples",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    matched-samples     = %s\n", v);
                if (zst_element_get_property(rx_sink, "mismatched-samples",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    mismatched-samples  = %s\n", v);
                if (zst_element_get_property(rx_sink, "integrity-pct",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    integrity           = %s\n", v);
                if (zst_element_get_property(rx_sink, "max-error",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    max-error           = %s\n", v);
                if (zst_element_get_property(rx_sink, "signal-rms-pct",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    signal-rms          = %s\n", v);
                if (zst_element_get_property(rx_sink, "signal-peak-pct",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    signal-peak         = %s\n", v);
                if (zst_element_get_property(rx_sink, "signal-frequency-hz",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    signal-frequency    = %s Hz\n", v);
                if (zst_element_get_property(rx_sink, "signal-ok",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    signal-ok           = %s\n", v);
            }

            /* RX video verify sink stats (decoded H.264) */
            if (rx_video_snk) {
                char v[64];
                printf("  RX video sink:\n");
                if (zst_element_get_property(rx_video_snk, "total-frames",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    total-frames        = %s\n", v);
                if (zst_element_get_property(rx_video_snk, "keyframes",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    keyframes           = %s\n", v);
                if (zst_element_get_property(rx_video_snk, "width",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    width               = %s\n", v);
                if (zst_element_get_property(rx_video_snk, "height",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    height              = %s\n", v);
                if (zst_element_get_property(rx_video_snk, "format",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    format              = %s\n", v);
                if (zst_element_get_property(rx_video_snk, "mean-luma",
                                             v, sizeof(v)) == ZST_OK)
                    printf("    mean-luma           = %s\n", v);
            }

            printf("\n");
            last_p = now;
        }
    }

    /* ── Shutdown ────────────────────────────────────────────────────── */
    printf("\n[STOP] Shutting down...\n");

    zst_scheduler_stop(g_scheduler);
    pthread_join(sthr, NULL);
    /* Drain any remaining flows and tear down coordinator route elements
     * before the pipeline state transitions to NULL. */
    drain_bus(pipe->bus, coordinator, &tx_flows, &rx_flows, &errs);
    if (coordinator) {
        (void)zst_dante_video_coordinator_remove_all_flows(coordinator);
    }
    (void)zst_dante_video_coordinator_attach_session(coordinator, NULL);
    session->bus = NULL;
    (void)zst_element_set_state(session, ZST_STATE_NULL);
    (void)zst_pipeline_set_state(pipe, ZST_STATE_NULL);

    printf("[STOP] Final:\n");
    if (tx_dep_sink) print_dep_ep(tx_dep_sink, "TX dep_sink");
    if (rx_dep_src)  print_dep_ep(rx_dep_src, "RX dep_src");

    /* Final integrity report */
    if (rx_sink) {
        rx_verify_sink_t* s = rx_sink->priv;
        printf("\n=== Audio Integrity Report ===\n");
        printf("  Total samples:   %llu\n",
               (unsigned long long)s->verify.total_samples);
        printf("  Matched:         %llu\n",
               (unsigned long long)s->verify.matched_samples);
        printf("  Mismatched:      %llu\n",
               (unsigned long long)s->verify.mismatched_samples);
        double pct = s->verify.total_samples > 0
            ? (double)s->verify.matched_samples * 100.0 /
              (double)s->verify.total_samples
            : 0.0;
        printf("  Integrity:       %.4f%%\n", pct);
        if (s->verify.max_error_value > 0) {
            printf("  Max error:       %.1f LSB (at sample %llu)\n",
                   s->verify.max_error_value,
                   (unsigned long long)s->verify.max_error_sample);
        }
        printf("  Tolerance:       ±%.0f LSB (±%.1f%%)\n",
               s->verify.tolerance * 2147483647.0,
               s->verify.tolerance * 100.0);
        double rms = s->channel0_samples > 0
            ? sqrt((double)(s->sum_sq / (long double)s->channel0_samples)) : 0.0;
        double rms_pct = rms * 100.0 / 2147483647.0;
        double peak_pct = (double)s->peak_abs * 100.0 / 2147483647.0;
        double seconds = s->channel0_samples > 0
            ? (double)s->channel0_samples / 48000.0 : 0.0;
        double hz = seconds > 0.0 ? (double)s->positive_crossings / seconds : 0.0;
        int signal_ok = s->channel0_samples >= 4800 && s->nonzero_samples > 0 &&
                        peak_pct >= 50.0 && peak_pct <= 95.0 &&
                        hz >= 420.0 && hz <= 460.0;
        printf("  Signal RMS:      %.2f%% FS\n", rms_pct);
        printf("  Signal peak:     %.2f%% FS\n", peak_pct);
        printf("  Signal freq:     %.2f Hz\n", hz);
        printf("==============================\n");
        if (pct >= 99.9 || signal_ok)
            printf("  [PASS] Audio signal OK (integrity %.4f%%, freq %.2f Hz)\n", pct, hz);
        else if (pct >= 99.0)
            printf("  [WARN] Audio integrity degraded (%.4f%%)\n", pct);
        else
            printf("  [FAIL] Audio signal FAILED (integrity %.4f%%, freq %.2f Hz)\n", pct, hz);
    }

    printf("  tx_flows=%d rx_flows=%d errors=%d\n", tx_flows, rx_flows, errs);

    /* Final RX video report */
    if (rx_video_snk) {
        rx_video_sink_t* s = rx_video_snk->priv;
        printf("\n=== RX Video Decode Report ===\n");
        printf("  Decoded frames: %llu\n",
               (unsigned long long)s->total_frames);
        printf("  Keyframes:      %llu\n",
               (unsigned long long)s->keyframes);
        printf("  Bytes:          %llu\n",
               (unsigned long long)s->total_bytes);
        if (s->have_geometry) {
            printf("  Geometry:       %ux%u (fmt=%u)\n",
                   s->width, s->height, s->format);
        } else {
            printf("  Geometry:       UNKNOWN (no frames decoded)\n");
        }
        printf("  Mean luma:      %.2f\n", s->mean_luma);
        if (s->total_frames > 0 && s->have_geometry)
            printf("  [PASS] RX video decode OK (%llu frames)\n",
                   (unsigned long long)s->total_frames);
        else
            printf("  [WARN] RX video: no decoded frames\n");
        printf("==============================\n");
    }

    if (coordinator)
        (void)zst_dante_video_coordinator_attach_session(coordinator, NULL);
    session->bus = NULL;
    zst_scheduler_destroy(g_scheduler); g_scheduler = NULL;
    zst_pipeline_destroy(pipe);
    zst_clock_unref(clock);

    printf("[STOP] Done.\n");
    return 0;
}
