# ── Options ──────────────────────────────────────────────────────────────
option(BUILD_TESTS     "Build test programs" ON)
option(BUILD_SHARED    "Build core as shared library" OFF)
option(ENABLE_PLUGINS  "Enable dlopen-based plugin loading" ON)
option(ENABLE_ONEAPI_ENCODER "Build Intel oneAPI video encoder element" OFF)
option(ENABLE_ONEAPI_DECODER "Build Intel oneAPI video decoder element" OFF)
option(ENABLE_VAAPI_ENCODER "Build Linux VA-API video encoder element" OFF)
option(ENABLE_VAAPI_DECODER "Build Linux VA-API video decoder element" OFF)
option(ENABLE_GLSINK "Build OpenGL display sink element" ON)
option(ENABLE_GLCOMPSINK "Build OpenGL compositor sink element" ON)
option(ENABLE_IPP_COMP_SINK "Build Intel IPP compositor sink element" OFF)
option(ENABLE_X11SINK "Build X11 display sink element" ON)
option(ENABLE_WEBRTC "Build WebRTC endpoint element (requires libdatachannel)" OFF)
option(ENABLE_ST2110 "Enable SMPTE ST2110 elements" ON)
option(ENABLE_DANTE "Build Dante DVR control and H.264 video routing support" OFF)
option(ENABLE_DANTE_DEP "Build Dante DEP shared-memory audio support" OFF)
